# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_animal', models.CharField(max_length=50)),
                ('favorite_color', models.CharField(max_length=50)),
                ('favorite_body_part', models.CharField(max_length=100)),
                ('favorite_texture', models.CharField(max_length=100)),
                ('favorite_smell', models.CharField(max_length=200)),
                ('favorite_taste', models.CharField(max_length=50)),
                ('favorite_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('signup_date', models.DateTimeField(verbose_name='signup date')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
    ]
